dist: xenial
language: python
git:
  depth: 3
cache: pip
matrix:
  # mark build as complete as soon as the versions that may not fail is finished
  fast_finish: true
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
install: # python installations
  - pip install -U pip wheel setuptools
  - pip install -U pytest
  - pip install -e .
  - pip install codecov
#script:
#  - pytest -sv .
#after_success:
#  - codecov
